### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by mattiaskagstrom** [rafariva/ANPR-Tensorflow#1]
test/00000000_XEU0654_0.png
test/00000001_IKO0436_1.png
test/00000002_EKV3553_0.png
test/00000003_IIK2857_0.png
test/00000004_OHB4399_0.png
test/00000005_RGR1232_0.png
test/00000006_IXM3273_0.png
test/00000007_OVD7764_1.png
test/00000008_HSL9028_1.png
test/00000009_EFZ5847_1.png
test/00000010_CZJ9110_1.png
test/00000011_VCX5125_0.png
test/00000012_ARX9236_1.png
test/00000013_NZH3659_0.png
test/00000014_RFQ2078_1.png
test/00000015_KKL6974_0.png
test/00000016_IIL9226_1.png
test/00000017_NVH5797_1.png
test/00000018_HJV8867_1.png
test/00000019_XTL0449_1.png
Traceback (most recent call last):
  File "C:\Users\swehu\Downloads\ANPR-Tensorflow-master\anpr\gen.py", line 284, in <module>
    for img_idx, (im, c, p) in enumerate(im_gen):
  File "C:\Users\swehu\Downloads\ANPR-Tensorflow-master\anpr\gen.py", line 275, in generate_ims
    yield generate_im(font_char_ims[random.choice(fonts)], num_bg_images)
  File "C:\Users\swehu\Downloads\ANPR-Tensorflow-master\anpr\gen.py", line 230, in generate_im
    bg = generate_bg(num_bg_images)
  File "C:\Users\swehu\Downloads\ANPR-Tensorflow-master\anpr\gen.py", line 217, in generate_bg
    bg = cv2.imread(fname, 0) / 255.
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'

**Comment by erijonhson** [comment]
You need to delete the file `bgs/readme.txt`

**Comment by rafariva** [comment]
The folder bgs only need to have images, you most delete de readme.txt
